### PR TITLE
Fix groonga 5.1.1 release post (en)

### PR DESCRIPTION
**Pull request by cosmo0920**
-  Remove localization URL
- Add a release note notice sentence
-  Use "equality comparison" to describe added new script syntax

### CODE REVIEW

**Comment by cosmo0920** [comment]
@myokoym Could you review this PR?

**Comment by myokoym** [comment]
Sorry, I'm reviewing.

**Comment by cosmo0920** [comment]
Ah, perhaps, we should send patch for this line: https://github.com/groonga/groonga.org/pull/22/files#diff-865022ed86e69b19efcc92f152b01c64R17 into groonga repository if this PR is accepted?

**Comment by cosmo0920** [comment]
I'm sorry for taking your time. There is no need to hurry...

**Comment by myokoym** [comment]
> Ah, perhaps, we should send patch for this line: https://github.com/groonga/groonga.org/pull/22/files#diff-865022ed86e69b19efcc92f152b01c64R17 into groonga repository if this PR is accepted?

i'm sorry, what does it mean?

**Comment by cosmo0920** [comment]
I mean that "Should this release post modification patches be applied Groonga's repository news.rst?".
Because this post seems to be originated from Groonga's news.rst.

**Comment by myokoym** [comment]
I understand. I think we don't need to apply it. `/ja/` is my typo when copying from `/ja/_posts/2015-12-29-groonga-5.1.1.md`.

**Comment by cosmo0920** [comment]
Thanks!

**Comment by myokoym** [comment]
Thanks for your help!

**Pull request merged**
